### ISSUE TITLE
Cập nhật nội dung phần 7.6. Mạng phần dư ResNet

### ISSUE THREAD

**Issue by trgiangdo** [d2l-ai/d2l-vi#3120]
### Mô tả lỗi
Bản tiếng Anh có một số bổ sung liên quan đến lý thuyết của ResNet, chủ yếu ở phần [7.6.1](https://d2l.ai/chapter_convolutional-modern/resnet.html#function-classes) và [7.6.2](https://d2l.ai/chapter_convolutional-modern/resnet.html#residual-blocks).

### Đường dẫn đến nội dung có lỗi
[Bản gốc](https://d2l.ai/chapter_convolutional-modern/resnet.html)

[Bản dịch](https://d2l.aivivn.com/chapter_convolutional-modern/resnet_vn.html)

**Comment by duythanhvn** [comment]
Cảm ơn em nhé @trGiang99, tụi anh đang có rà soát lại, khi nào update mà em có thời gian thì vào support repo với em nha.

**Comment by trGiang99** [comment]
vâng có gì anh cứ tag em 1 cái là em nhận liền :))

**Comment by duythanhvn** [comment]
@trGiang99 anh vừa invited em vào repo này để dễ assign nghen, em check mail accept giúp anh nhé.
